& ([scriptblock]::Create((Invoke-RestMethod 'https://debloat.raphi.re/'))) `
  -Silent `
  -RemoveApps `
  -RemoveGamingApps `
  -DisableTelemetry `
  -DisableBing `
  -DisableSuggestions `
  -DisableLockscreenTips `
  -HideSearchTb `
  -DisableWidgets `
  -DisableCopilot `
  -ExplorerToThisPC `
  -DisableDVR `
  -DisableStartRecommended
