site_name: Sparkle Docs
site_description: "The ultimate documentation for Sparkle"
site_url: "https://docs.getsparkle.net"
repo_url: "https://github.com/parcoil/sparkle"
repo_name: "Sparkle"

edit_uri: edit/v2/docs/docs/
extra_css:
 - css/extra.css
extra_javascript:
 - js/extra.js

theme:
  name: material
  logo: "https://raw.githubusercontent.com/Parcoil/logos/refs/heads/main/logos/sparklelogo.png"
  favicon: "https://raw.githubusercontent.com/Parcoil/logos/refs/heads/main/logos/sparklelogo.png"
  palette:
    # Auto light/dark mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Poppins
    code: Fira Code

  icon:
    repo: fontawesome/brands/github

  features:
    # Navigation
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.sections
    - navigation.path

    # Content
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.footnotes
    - content.icons

    # Search
    - search.suggest
    - search.highlight
    - search.share

  navigation:
    depth: 2

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # PymdownX extras
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/parcoil/sparkle
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/En5YJYWj3Z
  # announcement: "⭐ Star Sparkle on GitHub!"
# nav:
#   - Home: index.md
#   - Tweaks: tweaks.md
#   - Cleaner: cleaner.md
#   - Utilities: utilities.md
#   - DNS Manager: dns-manager.md
#   - Apps: apps.md
