site_name: Sparkle Docs
site_description: "The ultimate documentation for Sparkle"
site_url: "https://docs.getsparkle.net"
repo_url: "https://github.com/parcoil/sparkle"
repo_name: "Sparkle"

theme:
  name: material
  logo: "https://raw.githubusercontent.com/Parcoil/logos/refs/heads/main/logos/sparklelogo.png"
  favicon: "https://raw.githubusercontent.com/Parcoil/logos/refs/heads/main/logos/sparklelogo.png"
  palette:
    # Auto light/dark mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Poppins
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
  navigation.depth: 2
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/parcoil/sparkle
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/En5YJYWj3Z
  # announcement: "⭐ Star Sparkle on GitHub!"
# nav:
#   - Home: index.md
#   - Tweaks: tweaks.md
#   - Cleaner: cleaner.md
#   - Utilities: utilities.md
#   - DNS Manager: dns-manager.md
#   - Apps: apps.md
